name: "Framework size"
on: [pull_request]

jobs:
  build:
    name: iOS arm64
    runs-on: macos-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v1
        with:
          ref: ${{ github.base_ref }}
          clean: false

      - name: Build framework
        run: |
          xcodebuild -project Bugsnag.xcodeproj -configuration Release -scheme Bugsnag-iOS -destination generic/platform=iOS -derivedDataPath DerivedData -quiet clean build VALID_ARCHS=arm64
          eval $(stat -s DerivedData/Build/Products/Release-iphoneos/Bugsnag.framework/Bugsnag)
          echo $st_size > .size_before

      - name: Checkout PR branch
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
          clean: false

      - name: Build framework
        run: |
          xcodebuild -project Bugsnag.xcodeproj -configuration Release -scheme Bugsnag-iOS -destination generic/platform=iOS -derivedDataPath DerivedData -quiet clean build VALID_ARCHS=arm64
          eval $(stat -s DerivedData/Build/Products/Release-iphoneos/Bugsnag.framework/Bugsnag)
          echo $st_size > .size_after

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Danger
        run: bundle exec danger --dangerfile=.github/workflows/framework-size.danger --danger_id=framework-size
        env:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
