name: "Infer"
on: [pull_request]

jobs:
  build:
    name: Infer
    runs-on: macos-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
          clean: false

      - name: Infer
        run: make infer

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Danger
        run: bundle exec danger --dangerfile=.github/workflows/infer.danger --danger_id=infer
        env:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
